# Generated by Django 5.2.1 on 2025-05-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_review_alter_filelog_ip_address_alter_filelog_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
